config/routes.rb
Rails.application.routes.draw do  
  resources :listings

  root :to => 'pages#index'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks",:registrations => 'registrations' }

  resources :users, only: [:show]

  resources :photos, only: [:create, :destroy] do
    collection do
      get :list 
    end
  end

  resources :listings do 
    resources :reservations, only: [:create]
  end

  get '/setdate'=> 'reservations#setdate'
  get '/duplicate'=> 'reservations#duplicate'
  get '/reserved'=> 'reservations#index'
  get '/reservations'=> 'reservations#reserved'

  get 'manage-listing/:id/basics' => 'listings#basics', as: 'manage_listing_basics'
  get 'manage-listing/:id/description' => 'listings#description', as: 'manage_listing_description'
  get 'manage-listing/:id/address' => 'listings#address', as: 'manage_listing_address'
  get 'manage-listing/:id/price' => 'listings#price', as: 'manage_listing_price'
  get 'manage-listing/:id/photos' => 'listings#photos', as: 'manage_listing_photos'
  get 'manage-listing/:id/calendar' => 'listings#calendar', as: 'manage_listing_calendar'
  get 'manage-listing/:id/bankaccount' => 'listings#bankaccount', as: 'manage_listing_bankaccount'
  get 'manage-listing/:id/publish' => 'listings#publish', as: 'manage_listing_publish'
end

app/views/partial/_deviseErrorMsg.html.erb
<% unless resource.errors.empty? %>
    <script type="text/javascript">
        <% resource.errors.full_messages.each do|msg| %>
            toastr.error('<%= msg %>');
        <% end %>
    </script>
<% end %>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-device">
  <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if (!user_signed_in?) %>
           <li><%= link_to "シッターになる", new_listing_path %></li>
            <li><a href="#">2</a></li>
            <li><a href="#">3</a></li>
            <li><a href="#">4</a></li>
            <li><%= link_to "アカウント作成", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
        <% else %>
        <li><%= link_to "シッターになる", new_listing_path %></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <% if current_user.provider %>
                  <%=image_tag current_user.image, class:"img-circle profile-0"  %>
                  <%=current_user.name %>
                <% else %>
                  <%= current_user.email.split("@")[0]  %>
                <% end %>
                <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><%= link_to "リスティング", listings_path %></li>
                    <li><%= link_to "プロフィール", user_path(current_user) %></li>
                    <li><%= link_to "プロフィール編集", edit_user_registration_path %></li>
                    <li><%= link_to "預ける", reservations_path  %></li>
                    <li><%= link_to "予定", reserved_path %></li>
                    <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
                </ul>
            </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partial/_verticalnavbar.html.erb
<div class="sidebar-nav">
  <div class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-navbar-collapse">
        <label style="color: #fff;">他の項目を編集する</label>
      </button>
    </div>
    <div class="navbar-collapse collapse sidebar-navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%='active' if controller?("listings") && action?("basics") %>">
          <%= link_to "基本情報", manage_listing_basics_path(@listing) %>
        </li>
        <li class="<%='active' if controller?("listings") && action?("description") %>">
          <%= link_to "リスティングの内容", manage_listing_description_path(@listing) %>
        </li>
        <li class="<%='active' if controller?("listings") && action?("address") %>">
          <%= link_to "住所情報", manage_listing_address_path(@listing) %>
        </li>
        <li class="<%='active' if controller?("listings") && action?("price") %>">
          <%= link_to "料金", manage_listing_price_path(@listing) %>
        </li>
        <li class="<%='active' if controller?("listings") && action?("photos") %>">
          <%= link_to "写真", manage_listing_photos_path(@listing),data:{no_turbolink: true} %>
        </li>
        <li class="<%='active' if controller?("listings") && action?("calendar") %>">
          <%= link_to "カレンダー", manage_listing_calendar_path(@listing) %>
        </li>
        <li class="<%='active' if controller?("listings") && action?("bankaccount") %>">
          <%= link_to "受取口座情報", manage_listing_bankaccount_path(@listing) %>
        </li>
        <li class="<%='active' if controller?("listings") && action?("publish") %>">
          <%= link_to "編集", manage_listing_publish_path(@listing) %>
        </li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</div>